apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml
- ./ingress.yaml
images:
- name: docker.drtest.reisys.io/infra-test
  newTag: dcc4ea18b96b8562a1da87aad21d1ffe10b14407
